version: '3'
services:
  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:10
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=app
      - DB_PASS=app
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - postgresdata:/var/lib/postgresql
volumes:
  postgresdata: